document.addEventListener('DOMContentLoaded', async () => {
        await customElements.whenDefined('gmpx-store-locator');
        const locator = document.querySelector('gmpx-store-locator');
        locator.configureFromQuickBuilder(CONFIGURATION);
      });
// This code was automatically generated by the Google maps platform 'quick builder' https://console.cloud.google.com/google/maps-apis/build/locator-plus